### PR TITLE
Clang format changes

### PR DESCRIPTION
**Pull request by bsutherland333**
After reviewing the ROS2 and Google style guides, @avtoku and myself realized that the .clang-format file was not completely in line with their standards. This updates the .clang-format file and the code to fix that.

### CODE REVIEW

**Comment by avtoku** [comment]
It looks like ROS2 has instructions for linting your code that go beyond a clang-format call.
Personally I'd be inclined to just leave it as the stock google .clang-format if we are not going to go all the way.

**Comment by bsutherland333** [comment]
Ok, how about for now we just worry about the .clang-format file. Are you suggesting we leave it as is?

**Comment by avtoku** [comment]
> Ok, how about for now we just worry about the .clang-format file. Are you suggesting we leave it as is?

For Code that is compiled and run in the ROS2 environment, ROS2 recommends using their ament linter: https://docs.ros.org/en/humble/The-ROS2-Project/Contributing/Code-Style-Language-Versions.html#linters
This is beyond what I personally want to deal with for the rosflight_firmware.

For rosflight_firmware that lives outside the ROS2 environment we should not have to comply with ROS2 conventions. I think we should eventually use a few minor tweaks of the .clang-format Google format (like longer column limit), but for now let's just leave it as-is.

**Comment by bsutherland333** [comment]
@avtoku How does that look?

**Comment by avtoku** [comment]
> @avtoku How does that look?

Works for me.

**Review by avtoku — APPROVED** [review]
Looks good to me.

**Pull request merged**
